### ISSUE TITLE
Unexpected token: new

### ISSUE THREAD

**Issue by rem0g** [bitcoinjs/bip32-utils#8]
I'm relatively new to bip32-utils and it's the reason I'm finally learning Node.js. So far all good but I've encountered this problem and I don't know how to solve that, and I've took it from your examples. Thanks

```javascript
var account = new bip32utils.Account([
     new bip32utils.Chain(external.neutered())
    new bip32utils.Chain(internal.neutered())
])
```

Error message: 
    ^^^
    new bip32utils.Chain(internal.neutered())

**SyntaxError: Unexpected token new**

    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

Process finished with exit code 1
    ^^^

**Comment by dcousens** [comment]
You're missing a comma after `external.neutered())` ... thanks for pointing out the mistake in our README :+1:
